// C4D-DialogResource
DIALOG DLG_AUTH
{
  NAME IDS_AUTH_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
  
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 2;
    
    GROUP IDC_STATIC
    {
	
      NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 8, 4, 8, 10; 
      COLUMNS 1;
	  
	  STATICTEXT IDC_STATIC { CENTER_V; ALIGN_LEFT; SIZE 0, 1; }
	  
	  STATICTEXT IDC_STATIC { NAME IDS_SERNUM; CENTER_V; ALIGN_LEFT; }
	  MULTILINEEDIT IDC_CODEBOX_AUTH
      { ALIGN_TOP; ALIGN_LEFT; SIZE 410, 40;}
	  
      STATICTEXT IDC_STATIC { CENTER_V; ALIGN_LEFT; SIZE 0, 1; }
	  
	  GROUP IDC_STATIC
	  {
		COLUMNS 2;CENTER_H;
		BUTTON IDC_SERIAL { NAME IDS_BUTTON1; ALIGN_TOP; CENTER_H; SIZE 0, 16; }
		BUTTON IDC_PASTESERIAL { NAME IDS_BUTTON12; ALIGN_TOP; CENTER_H; SIZE 0, 16; }
	  }
	  
	  STATICTEXT IDC_STATIC { CENTER_V; ALIGN_LEFT; SIZE 0, 1; }
	  
      MULTILINEEDIT IDC_CODEBOX
      { ALIGN_TOP; ALIGN_LEFT; SIZE 410, 70;}
	  
    }
  }
  GROUP IDC_STATIC
	{
	  ALIGN_TOP; CENTER_H;
      BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 2;
	  
      BUTTON IDC_SUBMIT { NAME IDS_BUTTON2; ALIGN_TOP; ALIGN_RIGHT; SIZE 71, 16; }
      BUTTON IDC_CANCEL { NAME IDS_BUTTON3; ALIGN_TOP; ALIGN_LEFT; SIZE 71, 16; }
	}
}